import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './NavBar'
import { Container, Theme, ThemeContext, ThemePanel } from '@radix-ui/themes';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Navbar should be outside of the main content */}
      <Theme>

        <Navbar/>
        <main className='p-5'>
        <Container>
           {children}

        </Container>

        </main>
      </Theme>

      </body>
    </html>
  )
}
